"""modified uniqueness constraints to avoid duplicates

Revision ID: 1d5ba987a3d2
Revises: 0c02d33ecc69
Create Date: 2024-09-18 22:37:42.742843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d5ba987a3d2'
down_revision: Union[str, None] = '0c02d33ecc69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'venues', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venues', type_='unique')
    # ### end Alembic commands ###
